# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 189eb9ab5f1cc7793edf0a139f1ad75736b3cfbd444c964aee525197a7fdd411f03104016ab83b04d8d5a12a2a98ce36a6735200984dae0f60cc79267bc8cb09

test:
  secret_key_base: 916bbbf245ddc4f78469995ee6f8719240748c920034279b2bb42b1774b413ea26faa9191f040a1e96505842a21b2134cca70ef794ba9345a0e2b16607c7383c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
